part of 'package:activly/activly_app.dart';

const Duration kButtonLoadingDuration = Duration(milliseconds: 550);
const Duration kButtonFillDuration = Duration(milliseconds: 320);
const Duration kButtonLoaderRevealDelay = Duration(milliseconds: 380);
const double kFixedTopSpace = 51.0;

const Map<AppLanguage, TranslationCopy> kTranslations = {
  AppLanguage.en: TranslationCopy(
    appName: 'Activly',
    taglineLine1: 'The most playful way for kids',
    taglineLine2: 'to discover activities and make new friends.',
    continueWithGoogle: 'Continue with Google',
    continueWithApple: 'Continue with Apple',
    email: 'Email',
    phone: 'Phone',
    emailOrPhone: 'Email or Phone',
    fullName: 'Full Name',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    loginTitle: 'Welcome Back',
    loginSubtitle: 'Sign in to keep discovering activities and friends.',
    signInCta: 'Sign In',
    createAccountTitle: 'Create Account',
    createAccountSubtitle: 'Set up your account to start exploring activities.',
    createAccountCta: 'Create New Account',
    createNewAccount: 'Create New Account',
    dontHaveAccount: "Don't have an account?",
    createOne: 'Create one',
    byContinuing: 'By continuing, you agree to our',
    terms: 'Terms',
    privacyPolicy: 'Privacy Policy',
    alreadyHaveAccount: 'Already have an account?',
    forgotPassword: 'Forgot Password?',
    forgotPasswordTitle: 'Recover Password',
    forgotPasswordSubtitle:
        'Enter your email or phone to receive a verification code.',
    sendCode: 'Send Verification Code',
    otpTitle: 'Verify OTP',
    otpSubtitle: 'Enter the 6-digit code sent to',
    verifyCode: 'Verify Code',
    resendCode: 'Resend Code',
    changeContact: 'Change',
    resetPasswordTitle: 'Create New Password',
    resetPasswordSubtitle:
        'Your new password must be different from the previous one.',
    saveNewPassword: 'Save New Password',
    accountCreatedNotice: 'Account created successfully. Please sign in.',
    passwordResetSuccess: 'Password updated. You can now sign in.',
    backToSignIn: 'Back to Sign In',
    back: 'Back',
    skipForNow: 'Skip for Now',
    or: 'or',
    en: 'EN',
    ar: 'عربي',
  ),
  AppLanguage.ar: TranslationCopy(
    appName: 'أكتيفلي',
    taglineLine1: 'الطريقة الأكثر متعة للأطفال',
    taglineLine2: 'لاكتشاف الأنشطة وتكوين صداقات جديدة.',
    continueWithGoogle: 'المتابعة مع Google',
    continueWithApple: 'المتابعة مع Apple',
    email: 'البريد',
    phone: 'الهاتف',
    emailOrPhone: 'البريد أو الهاتف',
    fullName: 'الاسم الكامل',
    password: 'كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    loginTitle: 'مرحباً بعودتك',
    loginSubtitle: 'سجّل الدخول لمواصلة اكتشاف الأنشطة وتكوين الأصدقاء.',
    signInCta: 'تسجيل الدخول',
    createAccountTitle: 'إنشاء حساب',
    createAccountSubtitle: 'أنشئ حسابك لبدء استكشاف الأنشطة.',
    createAccountCta: 'إنشاء حساب جديد',
    createNewAccount: 'إنشاء حساب جديد',
    dontHaveAccount: 'ليس لديك حساب؟',
    createOne: 'أنشئ حساباً',
    byContinuing: 'بالمتابعة فإنك توافق على',
    terms: 'الشروط',
    privacyPolicy: 'سياسة الخصوصية',
    alreadyHaveAccount: 'هل لديك حساب بالفعل؟',
    forgotPassword: 'هل نسيت كلمة المرور؟',
    forgotPasswordTitle: 'استعادة كلمة المرور',
    forgotPasswordSubtitle: 'أدخل بريدك أو هاتفك لإرسال رمز التحقق.',
    sendCode: 'إرسال رمز التحقق',
    otpTitle: 'التحقق من الرمز',
    otpSubtitle: 'أدخل الرمز المكون من 6 أرقام المرسل إلى',
    verifyCode: 'تأكيد الرمز',
    resendCode: 'إعادة إرسال الرمز',
    changeContact: 'تعديل',
    resetPasswordTitle: 'إنشاء كلمة مرور جديدة',
    resetPasswordSubtitle: 'يجب أن تكون كلمة المرور الجديدة مختلفة عن السابقة.',
    saveNewPassword: 'حفظ كلمة المرور الجديدة',
    accountCreatedNotice: 'تم إنشاء الحساب بنجاح. يمكنك تسجيل الدخول الآن.',
    passwordResetSuccess: 'تم تحديث كلمة المرور. يمكنك تسجيل الدخول الآن.',
    backToSignIn: 'العودة لتسجيل الدخول',
    back: 'رجوع',
    skipForNow: 'تخطي للآن',
    or: 'أو',
    en: 'EN',
    ar: 'عربي',
  ),
};

const List<String> kVideoAssets = <String>[
  'assets/videos/indor-guitar-6s.mp4',
  'assets/videos/study-6s.mp4',
  'assets/videos/swimmig-pool-6s.mp4',
  'assets/videos/gaint-wheel-6s.mp4',
];
